### ISSUE TITLE
% not being diagnosed within the last year is 0

### ISSUE THREAD

**Issue by m-maheu-giroux** [mrc-ide/first90release#16]
Hi Jeff,

Did you want to remove the function to estimate probability of not being diagnosed within a year form the output table of Shiny90? These lines are commented out...

Also, Kim and Mary sent an email this morning (I haven't answered yet) saying that they could not see results past 2018... I haven't investigated yet beyond running the functions on my console and it is indeed displaying to 2025. Could it be related to the Shiny90 app?

Best,
Mathieu MG

https://github.com/mrc-ide/first90release/blob/1afa2d21c78b96e5dd5a81a233a03a9740d5a534/R/table_output.R#L50

**Comment by jeffeaton** [comment]
1) The `prb_dx_one_yr_cpp()` function was failing on Travis, so I commented it out so that we could merge the other updates. See issue #14. I suspect it's something related to `Rcpp` not being linked properly.

I would really like to get this back in but haven't had a chance to debug it yet. 

2) Yes that's possible. I think there was also mention that that programme data input did not have rows for 2018.  I've just done a quick search of the code and see 2018 hardcoded in several places:

* https://github.com/mrc-ide/shiny90/blob/b6b7436f7c63b5226f7c4e2746e725702c530897/src/server/survey_and_program_data.R#L127
* https://github.com/mrc-ide/shiny90/blob/bd200d72d55d6dc0ae5e9e8d8d31ee96681ea765/src/server/model_run.R#L261
* https://github.com/mrc-ide/shiny90/blob/2acfe6cd26e2d5d27b1734eb886b0062873286ac/src/server/downloads.R#L85

None of these immediately jump out to me as related to outputs -- so it might be somewhere else.

Thanks,
Jeff

**Comment by m-maheu-giroux** [comment]
Hi Jeff,

I suggest that we remove the default Rcpp function that is failing travis and that we use the R version of the same function. It takes twice as long to compute but this should not add more than a few seconds. The Rcpp version is only really important to calculate the CI which we don't need in this case. 

I can't update the master if you want... easy.

Mathieu

**Comment by jeffeaton** [comment]
Good idea -- yep, let's do that. Suggest not removing the Rcpp code, just change the wrapper function so that it is not called.

Thanks. Please do it on a branch and make a pull request.

Thanks,
Jeff

**Comment by jeffeaton** [comment]
This is addressed in release v1.3.3 (8ca7827)
